### ISSUE TITLE
make repo public

### ISSUE THREAD

**Issue by g-k** [mozilla-services/autograph-canary#55]
refs: https://github.com/mozilla-services/autograph-canary/issues/48

I ran a quick scan in https://github.com/mozilla-services/autograph-canary/issues/48#issuecomment-853860987 and don't think there's anything sensitive in here.

I spent awhile debugging deploys today and yesterday. `mirrorDockerImage` pulls build info from CircleCI but doesn't error for 404s (which CircleCI returns for private repos), so making this public will make it easier to deploy (alternatively we could set up a CircleCI API token).

**Comment by hwine** [comment]
done

**Comment by g-k** [comment]
Thanks Hal!
